name: deploy

# Controls when the action will run. Triggers the workflow on push
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    # Sync all files from GitHub Actions _work directory to web server root (html directory)
      # -a flag to sync subdirectories and keep permissions
      # --delete flag to delete files that are not present in the source directory
    - name: Sync files to web server root
      run: rsync -a --delete $GITHUB_WORKSPACE ~/html
